AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
  DisplayCopNames: true
Lint/Eval:
  Enabled: false
Metrics/LineLength:
  Max: 125
Rails/Output:
  Exclude:
    - 'lib/reviewit/**/*'
Style/Documentation:
  Enabled: false
Style/Not:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Style/EachWithObject:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
